Updating PHP versions
XOOPS/RegDom pull request #1
Opened 2024-06-30 02:42 UTC by mambax7

2024-06-30 23:58 UTC, geekwright requested changes
Looks good for the most part.

2024-06-30 23:58 UTC, geekwright commented on archive/effectiveTLDs.inc.php
We should just remove the whole archive directory. It has served it purpose.

2024-06-30 23:58 UTC, geekwright commented on composer.json
> +      "Geekwright\\Regdom\\": "src/"
Should be Xoops\\Regdom\\

2024-06-30 23:58 UTC, geekwright commented on src/PublicSuffixList.php
> +            if (PHP_VERSION_ID < 70000) {
Since we require 7.4 we should drop this if block. We are should always protect with **allowed_classes** for security.

2024-06-30 23:58 UTC, geekwright commented on composer.json
> +  "version": "1.0.10",
I would suggest 2.0.0-alpha-1 to start with. I usually just specify it in the repository tags instead.
[https://getcomposer.org/doc/04-schema.md#version](url)

2024-07-01 01:59 UTC, mambax7 commented
Thanks @geekwright

2024-07-06 22:48 UTC, merged